package hackerton.refactor.general.init;


import hackerton.refactor.domain.entity.business.BusinessCode;
import hackerton.refactor.domain.repository.BusinessCodeRepository;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Configuration
@RequiredArgsConstructor
public class SampleData {
    private final InitService initService;

    @PostConstruct
    @Profile("local")
    public void init() {
        initService.init();
    }

    @Service
    @Transactional
    @RequiredArgsConstructor
    static class InitService {
        private final BusinessCodeRepository businessCodeRepository;

        public void init() {
            businessCodeRepository.save(new BusinessCode("A", "농업, 임업 및 어업", "01", "농업", "0111", "곡물 및 기타 식량작물 재배업"));
            businessCodeRepository.save(new BusinessCode( "A", "농업, 임업 및 어업", "01", "농업", "0112", "채소, 화훼작물 및 과실작물 재배업"));
            businessCodeRepository.save(new BusinessCode("A", "농업, 임업 및 어업", "01", "농업", "0121", "소 사육업"));
            businessCodeRepository.save(new BusinessCode("A", "농업, 임업 및 어업", "01", "농업", "0122", "양돈 업"));
            businessCodeRepository.save(new BusinessCode("A", "농업, 임업 및 어업", "02", "임업", "0201", "영림업"));
            businessCodeRepository.save(new BusinessCode("A", "농업, 임업 및 어업", "03", "어업", "0311", "해면 어업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "10", "식료품 제조업", "1011", "도축, 육류 가공 및 저장 처리업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "10", "식료품 제조업", "1030", "과실 및 채소 절임 식품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "10", "식료품 제조업", "1071", "떡, 빵 및 과자류 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "11", "음료 제조업", "1111", "발효주 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "13", "섬유제품 제조업", "1321", "직물 직조 및 직물제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "14", "의복 제조업", "1411", "겉옷 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "15", "가죽, 가방 및 신발 제조업", "1512", "핸드백 및 기타 가죽제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "18", "인쇄 및 기록매체 복제업", "1811", "인쇄업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "20", "화학 물질 및 화학제품 제조업", "2041", "비누 및 세정제 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "21", "의료용 물질 및 의약품 제조업", "2110", "기초 의약물질 및 생물학적 제제 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "25", "금속 가공제품 제조업", "2511", "구조용 금속 제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "26", "전자 부품 및 통신장비 제조업", "2611", "반도체 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "26", "전자 부품 및 통신장비 제조업", "2622", "영상 및 음향 기기 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "28", "전기장비 제조업", "2811", "전동기, 발전기 및 전기 변환장치 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "29", "기타 기계 및 장비 제조업", "2911", "엔진 및 터빈 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "30", "자동차 및 트레일러 제조업", "3011", "자동차용 엔진 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "31", "기타 운송장비 제조업", "3111", "강선 건조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "32", "가구 제조업", "3201", "침대 및 관련제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "33", "기타 제품 제조업", "3311", "귀금속 및 관련제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "41", "종합 건설업", "4111", "주거용 건물 건설업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "41", "종합 건설업", "4112", "비주거용 건물 건설업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4211", "건물 철거 및 토사 정리 공사업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4220", "배관 및 냉·난방 공사업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4240", "인테리어 및 장식 공사업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "45", "자동차 판매업", "4511", "신차 판매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "45", "자동차 판매업", "4521", "자동차 부품 및 내장품 판매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4610", "상품 중개업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4631", "과실 및 채소 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4641", "의류 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4671", "연료 및 관련제품 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4711", "대형 마트"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4712", "체인화 편의점"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4721", "곡물, 식료품 및 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4741", "통신기기 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4781", "의류, 신발 및 신선식품 노점업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4791", "전자상거래업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "49", "육상 운송 및 파이프라인 운송업", "4923", "화물 자동차 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "49", "육상 운송 및 파이프라인 운송업", "4931", "택시 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "50", "수상 운송업", "5011", "외항 화물 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "51", "항공 운송업", "5110", "항공 여객 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "52", "창고 및 운송관련 서비스업", "5210", "보관 및 창고업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "55", "숙박업", "5510", "호텔업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "55", "숙박업", "5511", "여관업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "55", "숙박업", "5512", "펜션 및 민박업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5611", "한식 음식점업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5612", "일식 음식점업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5613", "중식 음식점업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5614", "서양식 음식점업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5619", "치킨 전문점"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5621", "커피 전문점"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5622", "제과점업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "58", "출판업", "5811", "서적 출판업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "58", "출판업", "5821", "게임 소프트웨어 제작업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "59", "영상·오디오 기록물 제작업", "5911", "영화 및 비디오물 제작업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "60", "방송업", "6010", "라디오 방송업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "61", "우편 및 통신업", "6121", "유선 통신업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "컴퓨터 프로그래밍 및 서비스업", "6201", "소프트웨어 개발 및 공급업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "컴퓨터 프로그래밍 및 서비스업", "6202", "컴퓨터 시스템 통합 자문 및 구축 서비스업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "63", "정보서비스업", "6311", "데이터베이스 및 온라인 정보 제공업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "63", "정보서비스업", "6391", "포털 및 기타 인터넷 정보 매개 서비스업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "64", "금융업", "6412", "은행 및 저축기관"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "65", "보험 및 연금업", "6511", "생명 보험업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "66", "금융 및 보험 관련 서비스업", "6612", "증권 및 선물 중개업"));
            businessCodeRepository.save(new BusinessCode( "L", "부동산업", "68", "부동산업", "6811", "부동산 임대업"));
            businessCodeRepository.save(new BusinessCode( "L", "부동산업", "68", "부동산업", "6821", "부동산 관리업"));
            businessCodeRepository.save(new BusinessCode( "L", "부동산업", "68", "부동산업", "6822", "부동산 자문 및 중개업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7110", "법무 관련 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7120", "회계 및 세무 관련 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7153", "광고 대행업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "72", "건축 및 엔지니어링 서비스업", "7211", "건축 설계 및 관련 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7320", "시장 조사 및 여론 조사 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업시설 관리 및 지원 서비스업", "74", "사업시설 관리업", "7410", "사업시설 유지·관리 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업시설 관리 및 지원 서비스업", "75", "사업지원 서비스업", "7511", "인력 공급업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업시설 관리 및 지원 서비스업", "75", "사업지원 서비스업", "7521", "경비 및 경호 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업시설 관리 및 지원 서비스업", "75", "사업지원 서비스업", "7531", "여행사 및 기타 여행 보조 서비스업"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8511", "일반 교과 학원"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8521", "예술 학원"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8561", "외국어 학원"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "86", "보건업", "8610", "병원"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "86", "보건업", "8620", "의원"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "87", "사회복지 서비스업", "8711", "노인 복지 시설"));
            businessCodeRepository.save(new BusinessCode( "R", "예술, 스포츠 및 여가관련 서비스업", "90", "창작, 예술 관련 서비스업", "9011", "공연 예술가"));
            businessCodeRepository.save(new BusinessCode( "R", "예술, 스포츠 및 여가관련 서비스업", "91", "스포츠 및 오락관련 서비스업", "9111", "스포츠 경기장 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술, 스포츠 및 여가관련 서비스업", "91", "스포츠 및 오락관련 서비스업", "9113", "체력단련시설 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술, 스포츠 및 여가관련 서비스업", "91", "스포츠 및 오락관련 서비스업", "9121", "노래연습장 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술, 스포츠 및 여가관련 서비스업", "91", "스포츠 및 오락관련 서비스업", "9122", "PC방 운영업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "95", "개인 및 가정용품 수리업", "9511", "컴퓨터 및 주변장치 수리업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "95", "개인 및 가정용품 수리업", "9521", "자동차 세차업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9611", "이용업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9612", "미용업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9613", "세탁업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9691", "장례식장 및 관련 서비스업"));
            businessCodeRepository.save(new BusinessCode( "T", "가구 내 고용활동", "97", "가구 내 고용활동", "9700", "가사 서비스업"));
            businessCodeRepository.save(new BusinessCode( "U", "국제 및 외국기관", "99", "국제 및 외국기관", "9900", "주한 외국 공관"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "10", "식료품 제조업", "1079", "기타 식료품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "11", "음료 제조업", "1120", "비알코올음료 및 얼음 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "13", "섬유제품 제조업", "1392", "침구 및 관련제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "14", "의복 제조업", "1419", "기타 의류 액세서리 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "16", "목재 및 나무제품 제조업", "1621", "일반 목공소"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "17", "종이 및 종이제품 제조업", "1712", "골판지 및 종이 상자 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "20", "화학 물질 및 화학제품 제조업", "2042", "화장품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "22", "고무 및 플라스틱제품 제조업", "2221", "포장용 플라스틱 제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "23", "비금속 광물제품 제조업", "2332", "시멘트 및 콘크리트 제품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "24", "1차 금속 제조업", "2411", "제철 및 제강업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "25", "금속 가공제품 제조업", "2592", "도금 및 금속 가공업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "26", "전자 부품 및 통신장비 제조업", "2621", "컴퓨터 및 주변장치 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "27", "의료, 정밀, 광학 기기 제조업", "2711", "의료용 기기 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "27", "의료, 정밀, 광학 기기 제조업", "2721", "안경 및 렌즈 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "28", "전기장비 제조업", "2841", "전구 및 조명장치 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "29", "기타 기계 및 장비 제조업", "2927", "반도체 제조용 기계 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "30", "자동차 및 트레일러 제조업", "3031", "자동차 신품 부품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "31", "기타 운송장비 제조업", "3192", "자전거 및 이륜자동차 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "32", "가구 제조업", "3202", "주방용 가구 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "33", "기타 제품 제조업", "3330", "운동 및 경기용구 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "33", "기타 제품 제조업", "3391", "인형 및 완구 제조업"));
            businessCodeRepository.save(new BusinessCode( "E", "수도, 하수 및 폐기물 처리업", "36", "수도업", "3601", "용수 정수 및 공급업"));
            businessCodeRepository.save(new BusinessCode( "E", "수도, 하수 및 폐기물 처리업", "38", "폐기물 수집운반 및 처리업", "3811", "일반 폐기물 수집운반업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "41", "종합 건설업", "4121", "도로 건설업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4231", "전기 공사업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4232", "정보통신 공사업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문직별 공사업", "4241", "도장 및 창호 공사업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "45", "자동차 판매업", "4522", "자동차 중고 부품 판매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4632", "육류 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4633", "수산물 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4642", "신발 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4643", "가전제품 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4644", "의약품 및 의료용품 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4651", "컴퓨터 및 소프트웨어 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매 및 상품 중개업", "4672", "금속광물 및 1차 금속제품 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4713", "슈퍼마켓"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4722", "육류 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4723", "수산물 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4731", "신발 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4732", "가방 및 기타 가죽제품 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4742", "가전제품 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4751", "철물 및 건설자재 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4761", "서적 및 잡지 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4782", "화장품 및 방향제 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4784", "안경 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4785", "애완동물 및 관련용품 소매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4792", "방문 판매업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "49", "육상 운송업", "4932", "버스 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "49", "육상 운송업", "4940", "이사화물 운송업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "52", "운송관련 서비스업", "5291", "주차장 운영업"));
            businessCodeRepository.save(new BusinessCode( "H", "운수 및 창고업", "52", "운송관련 서비스업", "5292", "구내 운송업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "55", "숙박업", "5590", "기타 숙박시설 운영업"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5615", "피자, 햄버거 및 샌드위치 점"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5616", "분식 및 김밥 전문점"));
            businessCodeRepository.save(new BusinessCode( "I", "숙박 및 음식점업", "56", "음식점 및 주점업", "5623", "생맥주 전문점"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "58", "출판업", "5812", "잡지 및 정기간행물 출판업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "58", "출판업", "5822", "응용 소프트웨어 개발 및 공급업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "59", "영상·오디오 기록물 제작업", "5912", "영화 및 비디오물 편집업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "59", "영상·오디오 기록물 제작업", "5920", "음악 및 오디오물 출판업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "60", "방송업", "6021", "지상파 방송업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "60", "방송업", "6022", "유선 및 위성 방송업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "IT 서비스업", "6203", "컴퓨터 시설 관리업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "63", "정보서비스업", "6312", "뉴스 제공업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "64", "금융업", "6491", "리스업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "64", "금융업", "6492", "할부금융업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "64", "금융업", "6499", "기타 금융업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "66", "금융관련 서비스업", "6611", "증권 거래소"));
            businessCodeRepository.save(new BusinessCode( "K", "금융 및 보험업", "66", "금융관련 서비스업", "6619", "기타 금융 지원 서비스업"));
            businessCodeRepository.save(new BusinessCode( "L", "부동산업", "68", "부동산업", "6812", "비주거용 건물 임대업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "70", "연구개발업", "7011", "물리, 화학 및 생물학 연구개발업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "70", "연구개발업", "7012", "농학 및 수산학 연구개발업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7130", "번역 및 통역 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7140", "경영 컨설팅업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "71", "전문 서비스업", "7151", "공공관계 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "72", "엔지니어링 서비스업", "7212", "토목 건설 설계 및 관련 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "72", "엔지니어링 서비스업", "7291", "측량 및 지도 제작업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7310", "디자인업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7330", "사진 촬영 및 처리업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7390", "그 외 기타 전문 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업지원 서비스업", "75", "사업지원 서비스업", "7591", "콜센터 및 텔레마케팅 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업지원 서비스업", "75", "사업지원 서비스업", "7592", "전시, 컨벤션 및 행사 대행업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업지원 서비스업", "75", "사업지원 서비스업", "7599", "기타 사업 지원 서비스업"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8541", "운전학원"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8550", "직업 기술 교육학원"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8562", "태권도장"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "86", "보건업", "8630", "치과 의원"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "86", "보건업", "8690", "기타 보건업"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업 및 사회복지 서비스업", "87", "사회복지 서비스업", "8721", "장애인 복지 시설"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "90", "창작 및 예술 관련 서비스업", "9021", "도서관 및 기록보존소 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "90", "창작 및 예술 관련 서비스업", "9022", "박물관 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "91", "스포츠 및 오락 서비스업", "9112", "골프장 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "91", "스포츠 및 오락 서비스업", "9114", "당구장 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "91", "스포츠 및 오락 서비스업", "9123", "테마파크 및 놀이공원 운영업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "94", "협회 및 단체", "9411", "산업 및 전문가 단체"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "94", "협회 및 단체", "9421", "종교 단체"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9614", "마사지업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9615", "네일아트업"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9619", "피부 관리실"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9692", "결혼 상담소"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9699", "그 외 기타 개인 서비스업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "IT 서비스업", "6204", "클라우드 컴퓨팅 서비스업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "IT 서비스업", "6205", "인공지능(AI) 솔루션 개발업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "62", "IT 서비스업", "6206", "블록체인 기술 기반 서비스업"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "63", "정보서비스업", "6313", "빅데이터 분석 및 제공업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "70", "연구개발업", "7013", "나노기술 연구개발업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "70", "연구개발업", "7020", "인문 및 사회과학 연구개발업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7391", "번역 및 통역 서비스업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문, 과학 및 기술 서비스업", "73", "기타 전문 서비스업", "7392", "매니지먼트 및 에이전시"));
            businessCodeRepository.save(new BusinessCode( "N", "사업지원 서비스업", "75", "사업지원 서비스업", "7593", "경품 및 마일리지 운영 서비스업"));
            businessCodeRepository.save(new BusinessCode( "N", "사업지원 서비스업", "75", "사업지원 서비스업", "7594", "사무 지원 서비스업"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8563", "온라인 교육 컨텐츠 제작업"));
            businessCodeRepository.save(new BusinessCode( "P", "교육 서비스업", "85", "교육 서비스업", "8564", "코딩 교육 학원"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "90", "창작 및 예술 관련 서비스업", "9012", "연예 매니지먼트업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "91", "스포츠 및 오락 서비스업", "9115", "스크린 골프장 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 및 스포츠 서비스업", "91", "스포츠 및 오락 서비스업", "9116", "요가 및 필라테스 센터"));
            businessCodeRepository.save(new BusinessCode( "S", "기타 개인 서비스업", "96", "기타 개인 서비스업", "9693", "반려동물 장묘 및 보호 서비스"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "10", "식료품 제조업", "1081", "건강보조식품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "20", "화학 물질 제조업", "2043", "친환경 세제 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "26", "전자 부품 제조업", "2630", "스마트폰 부품 제조업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "30", "자동차 제조업", "3012", "전기자동차 제조 및 조립업"));
            businessCodeRepository.save(new BusinessCode( "E", "폐기물 처리업", "38", "재활용업", "3821", "금속 폐기물 재활용업"));
            businessCodeRepository.save(new BusinessCode( "E", "폐기물 처리업", "38", "재활용업", "3822", "비금속 폐기물 재활용업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "41", "종합 건설업", "4122", "교량 및 터널 건설업"));
            businessCodeRepository.save(new BusinessCode( "F", "건설업", "42", "전문 공사업", "4250", "소방시설 공사업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매업", "4611", "농축산물 중개업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "46", "도매업", "4673", "건축 자재 도매업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4793", "자동판매기 운영업"));
            businessCodeRepository.save(new BusinessCode( "G", "도매 및 소매업", "47", "소매업", "4794", "중고 물품 소매업(구제 의류)"));
            businessCodeRepository.save(new BusinessCode( "H", "운수업", "49", "육상 운송업", "4950", "퍼스널 모빌리티 대여 서비스"));
            businessCodeRepository.save(new BusinessCode( "H", "운수업", "52", "운송 서비스", "5293", "물류 터미널 운영업"));
            businessCodeRepository.save(new BusinessCode( "I", "음식점업", "56", "음식점업", "5617", "출장 음식 서비스(케이터링)"));
            businessCodeRepository.save(new BusinessCode( "I", "음식점업", "56", "음식점업", "5618", "푸드트럭 운영업"));
            businessCodeRepository.save(new BusinessCode( "K", "금융업", "64", "금융업", "6420", "벤처 캐피탈(VC)"));
            businessCodeRepository.save(new BusinessCode( "K", "금융업", "66", "금융 서비스", "6613", "가상자산 거래소 운영업"));
            businessCodeRepository.save(new BusinessCode( "L", "부동산업", "68", "부동산업", "6813", "공유 오피스 운영업"));
            businessCodeRepository.save(new BusinessCode( "M", "전문 서비스업", "71", "전문 서비스업", "7160", "지식재산권(IP) 관리 서비스"));
            businessCodeRepository.save(new BusinessCode( "N", "사업 지원", "74", "시설 관리", "7421", "소독 및 해충 구제 서비스"));
            businessCodeRepository.save(new BusinessCode( "P", "교육업", "85", "교육업", "8570", "성인 취미 및 자기계발 학원"));
            businessCodeRepository.save(new BusinessCode( "Q", "보건업", "86", "보건업", "8640", "임상 병리 검사소"));
            businessCodeRepository.save(new BusinessCode( "R", "예술 서비스", "90", "예술 서비스", "9013", "무대 장치 및 행사 연출업"));
            businessCodeRepository.save(new BusinessCode( "S", "개인 서비스", "96", "개인 서비스", "9620", "간병 및 가사 서비스"));
            businessCodeRepository.save(new BusinessCode( "J", "정보통신업", "58", "출판업", "5823", "모바일 앱 개발 및 공급업"));
            businessCodeRepository.save(new BusinessCode( "C", "제조업", "21", "의약품 제조업", "2121", "완제 의약품 제조업"));
            businessCodeRepository.save(new BusinessCode( "G", "도소매업", "47", "소매업", "4714", "편의점 가맹본부"));
            businessCodeRepository.save(new BusinessCode( "I", "음식점업", "56", "주점업", "5624", "와인바 운영업"));
            businessCodeRepository.save(new BusinessCode( "M", "기술 서비스", "72", "엔지니어링", "7213", "조경 설계 및 감리 서비스업"));
            businessCodeRepository.save(new BusinessCode( "Q", "사회복지", "87", "복지 서비스", "8722", "아동 복지 시설 운영업"));
            businessCodeRepository.save(new BusinessCode( "R", "스포츠", "91", "스포츠 서비스", "9117", "수영장 운영업"));
            businessCodeRepository.save(new BusinessCode( "S", "개인 서비스", "95", "수리업", "9512", "가전제품 수리업"));
            businessCodeRepository.save(new BusinessCode( "G", "도소매업", "47", "소매업", "4799", "그 외 기타 무점포 소매업"));
        }

    }
}
