# 최대 클라이언트 수
maxclients 50000

# RDB / AOF OFF
save ""
appendonly no

# 메모리 제한 , eviction 정책
maxmemory 1gb
maxmemory-policy allkeys-lru

# 위험한 명령어 비활성화
rename-command KEYS ""

# ------------------------
# Hash, List, ZSet 압축 설정
# ------------------------

# Hash
hash-max-ziplist-entries 512
hash-max-ziplist-value 64

# List
list-max-ziplist-size -2
list-max-ziplist-value 64

# Sorted Set
zset-max-ziplist-entries 128
zset-max-ziplist-value 64