spring:
  profiles:
    active: local
  Jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:h2:tcp://localhost/~/hackerton
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        default_batch_fetch_size: 100
mail:
  host: smtp.naver.com
  port: 465
  username: zibi_official@naver.com
  password: U85DKZXRU792
  default-encoding: UTF-8

  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#Mail